### PR TITLE
tinyramfs: add some usb modules

### PR DESCRIPTION
**Pull request by dkwo**
This avoids a few undefined symbol errors from usb xhci.

### CODE REVIEW

**Comment by illiliti** [comment]
Thanks!

**Comment by illiliti** [comment]
I've decided to grant you write access to this repo. After you accept the invitation, you can push directly to master without my approval.

**Comment by dkwo** [comment]
Thank you!

**Comment by dkwo** [comment]
Do you think it's ok to tag 0.2.0 , so that I can e.g. update Void Linux's package?

**Comment by illiliti** [comment]
Yes, should be ok

**Pull request merged**
